### Base Site Prams ###
baseURL: "https://claytoneasley.org"
languageCode: en-us
title: Clayton Easley
theme: PaperModX
author:
  name: Clayton Easley
  
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

googleAnalytics: G-M50KSRMNSP

### Base Site Prams ###

### Search ###

outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary

###Search###

# allow html to render in md files
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  env: production
  Description: "Hi my name is Clayton. I am a student at the University of Massachusetts Lowell Studying Computer Engineering. interested in a plethora of things including but not limited to, programming,  electronics, art, welding, robots, and machine learning."
  defaultTheme: dark
  TocSide: left
  external: true
  custom_css:
    - css/img-tweaks.css


  profileMode:
        enabled: true
        title: "Computer Engineering Student"
          
        subtitle: >
          Hello and welcom to my site, I am currently a student at the University of Massachusetts Lowell! 
          I created this site to showcase my projects, ideas, and share some life experiences. Some projects are still in progress; excuse the underdeveloped posts. 
        
        imageWidth: 120 
        imageHeight: 120 

        buttons:
        - identifier: About Me
          name: About 
          url: /about/
        - identifier: projects
          name: Projects
          url: /projects/
        - identifier: Notes
          name: Notes
          url: /notes/

  contentDir: content
  
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowPostNavLinks: true

  ShowReadingTime: true
  ShowWordCount: true
  EnableImageZoom: true
  ShowCodeCopyButtons: true


  keywords: [Portfolio, Engineering, Computers, Blog]
  
  socialIcons:
    - name: github
      url: https://github.com/clayton14
    - name: linkedin
      url: https://www.linkedin.com/in/clayton-easley/
      # - name: email
      # url: mailto:askme@claytoneasley.org

  cover:
    linkFullImages: false
  
  editPost:
    URL: "https://github.com/clayton14/MySite2.0"
    Text: "Suggest Changes"
    appendFilePath: true 
   
menu:
  main:
  - identifier: Search
    name: Search 
    weight: 5
    url: /search/

  - identifier: categories
    name: All Categories
    url: /categories/
    weight: 3
  
  - identifier: projects
    name: Projects
    url: /projects/
    weight: 1
  
  - identifier: notes
    name: Notes
    url: /notes/
    weight: 2

